// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDUccq3rUEem5YENDz_0WhAws4STpqNGtM',
    appId: '1:875673694169:web:9832d1a16b46a92bc2f3c8',
    messagingSenderId: '875673694169',
    projectId: 'madpro-c81de',
    authDomain: 'madpro-c81de.firebaseapp.com',
    storageBucket: 'madpro-c81de.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAne43sk_MrCBfiu5ufDsEoRVQ6TnKgTso',
    appId: '1:875673694169:android:c199aed304749755c2f3c8',
    messagingSenderId: '875673694169',
    projectId: 'madpro-c81de',
    storageBucket: 'madpro-c81de.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCcYUxgDbQMyTs_dTceyjJT_3a_cxTXe_o',
    appId: '1:875673694169:ios:f10a21db4a471bcfc2f3c8',
    messagingSenderId: '875673694169',
    projectId: 'madpro-c81de',
    storageBucket: 'madpro-c81de.appspot.com',
    iosBundleId: 'com.example.flutterProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCcYUxgDbQMyTs_dTceyjJT_3a_cxTXe_o',
    appId: '1:875673694169:ios:58621a71fa4912e3c2f3c8',
    messagingSenderId: '875673694169',
    projectId: 'madpro-c81de',
    storageBucket: 'madpro-c81de.appspot.com',
    iosBundleId: 'com.example.flutterProject.RunnerTests',
  );
}
